### ISSUE TITLE
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap

### ISSUE THREAD

**Issue by vivianjeng** [arkworks-rs/circom-compat#61]
## execution
```sh
cargo test --package ark-circom --test groth16 --features circom-2 -- witness_generation_circom2 --exact --show-output
```

## version

cargo 1.78.0 (54d8815d0 2024-03-26)

## error
```sh
running 1 test
thread 'witness_generation_circom2' panicked at library/core/src/panicking.rs:156:5:
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:123:9
   3: core::panicking::panic_nounwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:156:5
   4: core::intrinsics::copy::precondition_check
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/intrinsics.rs:2799:21
   5: core::intrinsics::copy
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/intrinsics.rs:3073:9
   6: wasmer_vm::instance::InstanceHandle::new
             at /Users/zhengyawen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-vm-2.3.0/src/instance/mod.rs:968:9
   7: wasmer_engine::artifact::Artifact::instantiate
             at /Users/zhengyawen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-engine-2.3.0/src/artifact.rs:112:22
   8: wasmer::sys::module::Module::instantiate
             at /Users/zhengyawen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-2.3.0/src/sys/module.rs:282:35
   9: wasmer::sys::instance::Instance::new
             at /Users/zhengyawen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmer-2.3.0/src/sys/instance.rs:126:22
  10: ark_circom::witness::witness_calculator::WitnessCalculator::from_module
             at ./src/witness/witness_calculator.rs:89:34
  11: ark_circom::witness::witness_calculator::WitnessCalculator::from_file
             at ./src/witness/witness_calculator.rs:63:9
  12: ark_circom::witness::witness_calculator::WitnessCalculator::new
             at ./src/witness/witness_calculator.rs:57:9
  13: ark_circom::circom::builder::CircomConfig<E>::new
             at ./src/circom/builder.rs:28:20
  14: groth16::witness_generation_circom2
             at ./tests/groth16.rs:98:15
  15: groth16::witness_generation_circom2::{{closure}}
             at ./tests/groth16.rs:97:36
  16: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
error: test failed, to rerun pass `-p ark-circom --test groth16`
```

**Comment by Pratyush** [comment]
Hm I can't reproduce this at the moment; do you have any pointers (pun intended) I can follow?
