### ISSUE TITLE
witness_calculator error when loading wasm

### ISSUE THREAD

**Issue by cxyzhang0** [arkworks-rs/circom-compat#78]
Rust: 1.74.0
I used circom 2.2.0 to generate .wasm and .r1cs for the example multiplier2.circom. When I ran a test on them, the first line
    let cfg = CircomConfig::<Fr>::new(
        "./test-vectors/multiplier2.wasm",
        "./test-vectors/multiplier2.r1cs",
    )?;

resulted in the following error.

---- groth16_proof_multiplier2 stdout ----
thread 'groth16_proof_multiplier2' panicked at ~/Projects/arkworks-rs/circom-compat/src/circom/builder.rs:35:61:
called `Result::unwrap()` on an `Err` value: Error while importing "runtime"."printDebug": unknown import. Expected Function(FunctionType { params: [I32], results: [] })

Location:
    src/witness/witness_calculator.rs:91:24
stack backtrace:
   0:        0x1042b8254 - std::backtrace_rs::backtrace::libunwind::trace::he4f0a5f56afe8e37
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:        0x1042b8254 - std::backtrace_rs::backtrace::trace_unsynchronized::habb302958e80f800
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1042b8254 - std::sys_common::backtrace::_print_fmt::h9819d35e2a5cda77
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x1042b8254 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1f3776e0b5c7517d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1042db12c - core::fmt::rt::Argument::fmt::h626862aa6242248a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:        0x1042db12c - core::fmt::write::heedef092c8c0962e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:        0x1042b4158 - std::io::Write::write_fmt::h8e9ee1c6e6a7d36d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:        0x1042b80ac - std::sys_common::backtrace::_print::ha0f584bc7bfb9d2b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1042b80ac - std::sys_common::backtrace::print::h417292deb95532ed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x1042b9650 - std::panicking::default_hook::{{closure}}::h0cb68f1228c4613a
  10:        0x1042b929c - std::panicking::default_hook::h24535936bc1f51de
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:295:9
  11:        0x1021b9874 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4a11eb0407408336
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  12:        0x1021b9874 - test::test_main::{{closure}}::hc692fb3a0d2a3405
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:137:21
  13:        0x1042b9f30 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd294eb67051ac295
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
  14:        0x1042b9f30 - std::panicking::rust_panic_with_hook::h5db4d2345b297bed
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
  15:        0x1042b9938 - std::panicking::begin_panic_handler::{{closure}}::h3fd558f09a0d5492
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  16:        0x1042b86dc - std::sys_common::backtrace::__rust_end_short_backtrace::hfc76eebe1ce501b2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  17:        0x1042b96a8 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  18:        0x104366d00 - core::panicking::panic_fmt::hc2b459a5bd3dce66
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  19:        0x104367100 - core::result::unwrap_failed::h88d7eb352f20b747
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
  20:        0x10211ab64 - core::result::Result<T,E>::unwrap::hde8a2aa24b6ccbf9
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
  21:        0x10211ab64 - ark_circom::circom::builder::CircomConfig<F>::new::he4ed8dbc274aa37d
                               at ~/Projects/arkworks-rs/circom-compat/src/circom/builder.rs:35:20
  22:        0x102138a84 - groth16::groth16_proof_sean_multiplier2::{{closure}}::ha08931eed90497b6
                               at ~/Projects/arkworks-rs/circom-compat/tests/groth16.rs:114:15
  23:        0x10213678c - <core::pin::Pin<P> as core::future::future::Future>::poll::he2dcc2636edf9a85
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  24:        0x102136728 - <core::pin::Pin<P> as core::future::future::Future>::poll::h8ed5fc94f5d4966d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  25:        0x102125b38 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}::h71aa59b4c61123fd
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:57
  26:        0x102125920 - tokio::runtime::coop::with_budget::hf7c014d8f04b3d36
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  27:        0x102125920 - tokio::runtime::coop::budget::h00acbc7c1c5b4912
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  28:        0x102125920 - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::hc47d63e5da16cb06
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:25
  29:        0x102123934 - tokio::runtime::scheduler::current_thread::Context::enter::h443b735b055362f0
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:410:19
  30:        0x10212530c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::hed4c32d9db5d256b
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:650:36
  31:        0x102124a34 - tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}::h8ba78d97fbe6126c
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:68
  32:        0x10211c40c - tokio::runtime::context::scoped::Scoped<T>::set::h47f6aee1d5c96b92
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
  33:        0x10208f23c - tokio::runtime::context::set_scheduler::{{closure}}::hb2adf9bbe1e941a4
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
  34:        0x10212a320 - std::thread::local::LocalKey<T>::try_with::h7bf59e6eec2b9420
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:286:12
  35:        0x102127920 - std::thread::local::LocalKey<T>::with::h5f819ca0f89bf638
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:9
  36:        0x10208f1b8 - tokio::runtime::context::set_scheduler::h73d8f230ce396312
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
  37:        0x10212452c - tokio::runtime::scheduler::current_thread::CoreGuard::enter::h7606470ad38fae0f
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:27
  38:        0x102124acc - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h71f988e8fba7cb69
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:638:19
  39:        0x102123148 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}::hfce741bd4c7fcd9c
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:175:28
  40:        0x1020d7bcc - tokio::runtime::context::runtime::enter_runtime::h6f41f52ee658b2bc
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  41:        0x102122da0 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::h75f2cd82e7d12c98
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:167:9
  42:        0x1020c3f0c - tokio::runtime::runtime::Runtime::block_on::hdf10b655c1e66b91
                               at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:311:47
  43:        0x1020b81c8 - groth16::groth16_proof_sean_multiplier2::h2c3dd0021cffd387
                               at ~/Projects/arkworks-rst/rust/arkworks-rs/circom-compat/tests/groth16.rs:144:5
  44:        0x1021389d4 - groth16::groth16_proof_sean_multiplier2::{{closure}}::h35b903d7da8687bb
                               at ~/Projects/arkworks-rs/circom-compat/tests/groth16.rs:113:46
  45:        0x1020294f4 - core::ops::function::FnOnce::call_once::hb5fd88665f1f15c4
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  46:        0x1021bd6b0 - core::ops::function::FnOnce::call_once::h454722b9c172c736
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  47:        0x1021bd6b0 - test::__rust_begin_short_backtrace::h17f7c1515df0a235
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:623:18
  48:        0x1021bcf68 - test::run_test_in_process::{{closure}}::h5a3bff2a31f1e537
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:646:60
  49:        0x1021bcf68 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0b8de321532955ff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  50:        0x1021bcf68 - std::panicking::try::do_call::h13be6e26c2c3c68b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  51:        0x1021bcf68 - std::panicking::try::h059f88e723f89b5f
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  52:        0x1021bcf68 - std::panic::catch_unwind::hd330bc7815defc79
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  53:        0x1021bcf68 - test::run_test_in_process::hbf8971b18489e04f
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:646:27
  54:        0x1021bcf68 - test::run_test::{{closure}}::h76b410377c0b2f35
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:569:43
  55:        0x10218f310 - test::run_test::{{closure}}::h75c675bf03d043b7
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/test/src/lib.rs:597:41
  56:        0x10218f310 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc1611c1e78c48a9e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  57:        0x1021937a4 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h6fd9659b467a4412
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:542:17
  58:        0x1021937a4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hd27e10541a82d5a4
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  59:        0x1021937a4 - std::panicking::try::do_call::h931e60cf6dcb794c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  60:        0x1021937a4 - std::panicking::try::h1cededc46a115020
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  61:        0x1021937a4 - std::panic::catch_unwind::h06fe2d622231a23b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  62:        0x1021937a4 - std::thread::Builder::spawn_unchecked_::{{closure}}::hba73937f69dfea1a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:541:30
  63:        0x1021937a4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e4b8cf5c05495ef
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  64:        0x1042befe4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h435242b988184cd5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  65:        0x1042befe4 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e377725be3abcb1
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
  66:        0x1042befe4 - std::sys::pal::unix::thread::Thread::new::thread_start::h50a0ef5291b272f3
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
  67:        0x183cae034 - __pthread_joiner_wake

**Comment by cxyzhang0** [comment]
Looks like .wasm generated from circom 2.1.9 works.
